#!/bin/bash

set -e

cat >config.ninja <<EOT
# This file is generated by bootstrap.sh.
conf_cflags = -O2
conf_ldflags = -s
# When developing:
# conf_cflags = -g -Wall
# conf_ldlags = -g -Wall
EOT
srcs=$(ls src/*.cc | grep -v test)
echo "Building stage 1..."
g++ -Wno-deprecated -o ninja.bootstrap $srcs
echo "Building final result..."
./ninja.bootstrap ninja
rm ninja.bootstrap
echo "Done!"
