<!-- This soup of XML is the minimum customization necessary to make the
     autogenerated manual look ok. -->
<!DOCTYPE xsl:stylesheet [
<!ENTITY css SYSTEM "style.css">
]>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		version='1.0'>
  <xsl:import href="http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl"/>
  <xsl:template name="user.head.content"><style>&css;</style></xsl:template>
  <xsl:template name="body.attributes"></xsl:template>
  <xsl:param name="generate.toc" select="'book toc'"/>
  <xsl:param name="chapter.autolabel" select="0" />
  <xsl:param name="toc.list.type">ul</xsl:param>

  <xsl:output method="html" encoding="utf-8" indent="no"
              doctype-public=""/>
</xsl:stylesheet>
