Ninja: build_log_test.cc File Reference
build_log_test.cc File Reference
#include "build_log.h"
#include "test.h"
Classes
struct BuildLogTest
Functions
TEST_F (BuildLogTest, WriteRead)
TEST_F (BuildLogTest, DoubleEntry)
TEST_F (BuildLogTest, Truncate)
TEST_F (BuildLogTest, UpgradeV2)
Variables
static const char kTestFilename [] = "BuildLogTest-tempfile"
Function Documentation
TEST_F (BuildLogTest , WriteRead)
Definition at line 40 of file build_log_test.cc.
References AssertParse(), BuildLog::Close(), kTestFilename, BuildLog::Load(), BuildLog::log_, BuildLog::LookupByOutput(), BuildLog::OpenForWrite(), and BuildLog::RecordCommand().
TEST_F (BuildLogTest , DoubleEntry)
Definition at line 68 of file build_log_test.cc.
References BuildLog::LogEntry::command, kTestFilename, BuildLog::Load(), and BuildLog::LookupByOutput().
TEST_F (BuildLogTest , Truncate)
Definition at line 84 of file build_log_test.cc.
References AssertParse(), BuildLog::Close(), kTestFilename, BuildLog::Load(), BuildLog::OpenForWrite(), and BuildLog::RecordCommand().
TEST_F (BuildLogTest , UpgradeV2)
Definition at line 119 of file build_log_test.cc.
References BuildLog::LogEntry::command, BuildLog::LogEntry::end_time, kTestFilename, BuildLog::Load(), BuildLog::LookupByOutput(), BuildLog::LogEntry::restat_mtime, and BuildLog::LogEntry::start_time.
Variable Documentation
const char kTestFilename[] = "BuildLogTest-tempfile" [static]
Definition at line 30 of file build_log_test.cc.
Referenced by BuildLogTest::TearDown(), and TEST_F().