Ninja: clean_test.cc File Reference
clean_test.cc File Reference
#include "clean.h"
#include "build.h"
#include "test.h"
Classes
struct CleanTest
Functions
TEST_F (CleanTest, CleanAll)
TEST_F (CleanTest, CleanAllDryRun)
TEST_F (CleanTest, CleanTarget)
TEST_F (CleanTest, CleanTargetDryRun)
TEST_F (CleanTest, CleanRule)
TEST_F (CleanTest, CleanRuleDryRun)
TEST_F (CleanTest, CleanRuleGenerator)
TEST_F (CleanTest, CleanFailure)
Function Documentation
TEST_F (CleanTest , CleanAll)
Definition at line 28 of file clean_test.cc.
References AssertParse(), Cleaner::CleanAll(), and Cleaner::cleaned_files_count().
TEST_F (CleanTest , CleanAllDryRun)
Definition at line 58 of file clean_test.cc.
References AssertParse(), Cleaner::CleanAll(), and Cleaner::cleaned_files_count().
TEST_F (CleanTest , CleanTarget)
Definition at line 89 of file clean_test.cc.
References AssertParse(), Cleaner::cleaned_files_count(), and Cleaner::CleanTarget().
TEST_F (CleanTest , CleanTargetDryRun)
Definition at line 119 of file clean_test.cc.
References AssertParse(), Cleaner::cleaned_files_count(), and Cleaner::CleanTarget().
TEST_F (CleanTest , CleanRule)
Definition at line 150 of file clean_test.cc.
References AssertParse(), Cleaner::cleaned_files_count(), and Cleaner::CleanRule().
TEST_F (CleanTest , CleanRuleDryRun)
Definition at line 182 of file clean_test.cc.
References AssertParse(), Cleaner::cleaned_files_count(), and Cleaner::CleanRule().
TEST_F (CleanTest , CleanRuleGenerator)
Definition at line 215 of file clean_test.cc.
References AssertParse(), Cleaner::CleanAll(), and Cleaner::cleaned_files_count().
TEST_F (CleanTest , CleanFailure)
Definition at line 237 of file clean_test.cc.
References AssertParse(), and Cleaner::CleanAll().