Ninja: graph_test.cc File Reference
graph_test.cc File Reference
#include "graph.h"
#include "test.h"
Classes
struct GraphTest
Functions
TEST_F (GraphTest, MissingImplicit)
TEST_F (GraphTest, ModifiedImplicit)
TEST_F (GraphTest, FunkyMakefilePath)
TEST_F (GraphTest, ExplicitImplicit)
TEST_F (GraphTest, PathWithCurrentDirectory)
TEST_F (GraphTest, RootNodes)
Function Documentation
TEST_F (GraphTest , MissingImplicit)
Definition at line 23 of file graph_test.cc.
References AssertParse(), and Edge::RecomputeDirty().
TEST_F (GraphTest , ModifiedImplicit)
Definition at line 40 of file graph_test.cc.
References AssertParse(), and Edge::RecomputeDirty().
TEST_F (GraphTest , FunkyMakefilePath)
Definition at line 56 of file graph_test.cc.
References AssertParse(), and Edge::RecomputeDirty().
TEST_F (GraphTest , ExplicitImplicit)
Definition at line 77 of file graph_test.cc.
References AssertParse(), and Edge::RecomputeDirty().
TEST_F (GraphTest , PathWithCurrentDirectory)
Definition at line 101 of file graph_test.cc.
References AssertParse(), and Edge::RecomputeDirty().
TEST_F (GraphTest , RootNodes)
Definition at line 119 of file graph_test.cc.
References AssertParse().