Ninja: ninja.cc File Reference
ninja.cc File Reference
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <getopt.h>
#include "browse.h"
#include "build.h"
#include "build_log.h"
#include "clean.h"
#include "graph.h"
#include "graphviz.h"
#include "parsers.h"
#include "state.h"
#include "util.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 400 of file ninja.cc.
References Builder::AddTarget(), Builder::AlreadyUpToDate(), State::bindings_, Builder::Build(), State::build_log_, BuildConfig::dry_run, Error(), Fatal(), getopt_long(), BuildLog::Load(), ManifestParser::Load(), BindingEnv::LookupVariable(), MakeDir(), no_argument, BuildLog::OpenForWrite(), optarg, optind, BuildConfig::parallelism, BuildLog::SetConfig(), BuildConfig::swallow_failures, BuildConfig::VERBOSE, and BuildConfig::verbosity.