Ninja: parsers_test.cc File Reference
parsers_test.cc File Reference
#include "parsers.h"
#include <gtest/gtest.h>
#include "graph.h"
#include "state.h"
Classes
struct ParserTest
Functions
TEST (MakefileParser, Basic)
TEST (MakefileParser, EarlyNewlineAndWhitespace)
TEST (MakefileParser, Continuation)
TEST_F (ParserTest, Empty)
TEST_F (ParserTest, Rules)
TEST_F (ParserTest, Variables)
TEST_F (ParserTest, VariableScope)
TEST_F (ParserTest, Continuation)
TEST_F (ParserTest, Backslash)
TEST_F (ParserTest, Comment)
TEST_F (ParserTest, Dollars)
TEST_F (ParserTest, CanonicalizeFile)
TEST_F (ParserTest, PathVariables)
TEST_F (ParserTest, CanonicalizePaths)
TEST_F (ParserTest, ReservedWords)
TEST_F (ParserTest, Errors)
TEST_F (ParserTest, MultipleOutputs)
TEST_F (ParserTest, SubNinja)
TEST_F (ParserTest, MissingSubNinja)
TEST_F (ParserTest, Include)
TEST_F (ParserTest, Implicit)
TEST_F (ParserTest, OrderOnly)
TEST_F (ParserTest, DefaultDefault)
TEST_F (ParserTest, DefaultStatements)
Function Documentation
TEST (MakefileParser , Basic)
Definition at line 490 of file parsers_test.cc.
References StringPiece::AsString(), MakefileParser::ins_, MakefileParser::out_, and MakefileParser::Parse().
TEST (MakefileParser , EarlyNewlineAndWhitespace)
Definition at line 501 of file parsers_test.cc.
References MakefileParser::Parse().
TEST (MakefileParser , Continuation)
Definition at line 511 of file parsers_test.cc.
References StringPiece::AsString(), MakefileParser::ins_, MakefileParser::out_, and MakefileParser::Parse().
TEST_F (ParserTest , Empty)
Definition at line 47 of file parsers_test.cc.
References AssertParse().
TEST_F (ParserTest , Rules)
Definition at line 51 of file parsers_test.cc.
References AssertParse().
TEST_F (ParserTest , Variables)
Definition at line 67 of file parsers_test.cc.
References AssertParse().
TEST_F (ParserTest , VariableScope)
Definition at line 92 of file parsers_test.cc.
References AssertParse().
TEST_F (ParserTest , Continuation)
Definition at line 109 of file parsers_test.cc.
References AssertParse().
TEST_F (ParserTest , Backslash)
Definition at line 124 of file parsers_test.cc.
References AssertParse().
TEST_F (ParserTest , Comment)
Definition at line 133 of file parsers_test.cc.
References AssertParse().
TEST_F (ParserTest , Dollars)
Definition at line 140 of file parsers_test.cc.
References AssertParse().
TEST_F (ParserTest , CanonicalizeFile)
Definition at line 152 of file parsers_test.cc.
References AssertParse().
TEST_F (ParserTest , PathVariables)
Definition at line 166 of file parsers_test.cc.
References AssertParse().
TEST_F (ParserTest , CanonicalizePaths)
Definition at line 177 of file parsers_test.cc.
References AssertParse().
TEST_F (ParserTest , ReservedWords)
Definition at line 189 of file parsers_test.cc.
References AssertParse().
TEST_F (ParserTest , Errors)
Definition at line 197 of file parsers_test.cc.
References ManifestParser::Parse().
TEST_F (ParserTest , MultipleOutputs)
Definition at line 384 of file parsers_test.cc.
References ManifestParser::Parse().
TEST_F (ParserTest , SubNinja)
Definition at line 395 of file parsers_test.cc.
References AssertParse().
TEST_F (ParserTest , MissingSubNinja)
Definition at line 420 of file parsers_test.cc.
References ManifestParser::Parse().
TEST_F (ParserTest , Include)
Definition at line 428 of file parsers_test.cc.
References AssertParse().
TEST_F (ParserTest , Implicit)
Definition at line 439 of file parsers_test.cc.
References AssertParse(), and Edge::is_implicit().
TEST_F (ParserTest , OrderOnly)
Definition at line 448 of file parsers_test.cc.
References AssertParse(), and Edge::is_order_only().
TEST_F (ParserTest , DefaultDefault)
Definition at line 457 of file parsers_test.cc.
References AssertParse().
TEST_F (ParserTest , DefaultStatements)
Definition at line 470 of file parsers_test.cc.
References AssertParse().