Ninja: StateTestWithBuiltinRules Struct Reference
StateTestWithBuiltinRules Struct Reference
A base test fixture that includes a State object with a builtin "cat" rule.
#include <test.h>
Public Member Functions
Node * GetNode (const string &path)
StateTestWithBuiltinRules ()
Public Attributes
State state_
Detailed Description
A base test fixture that includes a State object with a builtin "cat" rule.
Definition at line 29 of file test.h.
Constructor & Destructor Documentation
StateTestWithBuiltinRules::StateTestWithBuiltinRules ()
Definition at line 19 of file test.cc.
References AssertParse(), and state_.
Member Function Documentation
Node * StateTestWithBuiltinRules::GetNode (const string & path)
Definition at line 25 of file test.cc.
References State::GetNode(), and state_.
Referenced by BuildTest::Dirty().
Member Data Documentation
State StateTestWithBuiltinRules::state_
Definition at line 33 of file test.h.
Referenced by BuildTest::BuildTest(), BuildWithLogTest::BuildWithLogTest(), GetNode(), and StateTestWithBuiltinRules().
The documentation for this struct was generated from the following files:
test.h
test.cc