Ninja: Env Struct Reference
Env Struct Reference
An interface for a scope for variable (e.g. "$foo") lookups.
#include <eval_env.h>
Public Member Functions
virtual string LookupVariable (const string &var)=0
virtual ~Env ()
Detailed Description
An interface for a scope for variable (e.g. "$foo") lookups.
Definition at line 24 of file eval_env.h.
Constructor & Destructor Documentation
virtual Env::~Env () [inline, virtual]
Definition at line 25 of file eval_env.h.
Member Function Documentation
virtual string Env::LookupVariable (const string & var) [pure virtual]
Implemented in EdgeEnv, and BindingEnv.
Referenced by EvalString::Evaluate(), BindingEnv::LookupVariable(), and EdgeEnv::LookupVariable().
The documentation for this struct was generated from the following file:
eval_env.h