Ninja: RealDiskInterface Struct Reference
RealDiskInterface Struct Reference
Implementation of DiskInterface that actually hits the disk.
#include <disk_interface.h>
Public Member Functions
virtual bool MakeDir (const std::string &path)
Create a directory, returning false on failure.
bool MakeDirs (const std::string &path)
Create all the parent directories for path; like mkdir -p `basename path`.
virtual std::string ReadFile (const std::string &path, std::string *err)
Read a file to a string. Fill in |err| on error.
virtual int RemoveFile (const std::string &path)
Remove the file named path.
virtual int Stat (const std::string &path)
stat() a file, returning the mtime, or 0 if missing and -1 on other errors.
virtual ~RealDiskInterface ()
Detailed Description
Implementation of DiskInterface that actually hits the disk.
Definition at line 50 of file disk_interface.h.
Constructor & Destructor Documentation
virtual RealDiskInterface::~RealDiskInterface () [inline, virtual]
Definition at line 51 of file disk_interface.h.
Member Function Documentation
bool RealDiskInterface::MakeDir (const std::string & path) [virtual]
Create a directory, returning false on failure.
Implements DiskInterface.
Definition at line 79 of file disk_interface.cc.
References Error().
bool DiskInterface::MakeDirs (const std::string & path) [inherited]
Create all the parent directories for path; like mkdir -p `basename path`.
Definition at line 45 of file disk_interface.cc.
References DiskInterface::MakeDir(), and DiskInterface::Stat().
Referenced by Builder::StartEdge().
std::string RealDiskInterface::ReadFile (const std::string & path, std::string * err) [virtual]
Read a file to a string. Fill in |err| on error.
Implements DiskInterface.
Definition at line 87 of file disk_interface.cc.
int RealDiskInterface::RemoveFile (const std::string & path) [virtual]
Remove the file named path.
It behaves like 'rm -f path' so no errors are reported if it does not exists.
Returns:
0 if the file has been removed, 1 if the file does not exist, and -1 if an error occurs.
Implements DiskInterface.
Definition at line 98 of file disk_interface.cc.
References Error().
int RealDiskInterface::Stat (const std::string & path) [virtual]
stat() a file, returning the mtime, or 0 if missing and -1 on other errors.
Implements DiskInterface.
Definition at line 64 of file disk_interface.cc.
References Error().
The documentation for this struct was generated from the following files:
disk_interface.h
disk_interface.cc