Ninja: StatCache Struct Reference
StatCache Struct Reference
Mapping of path -> FileStat.
#include <stat_cache.h>
Public Types
typedef ExternalStringHashMap
< FileStat * >::Type Paths
Public Member Functions
void Dump ()
Dump the mapping to stdout (useful for debugging).
FileStat * GetFile (const std::string &path)
void Invalidate ()
Public Attributes
Paths paths_
Detailed Description
Mapping of path -> FileStat.
Definition at line 27 of file stat_cache.h.
Member Typedef Documentation
typedef ExternalStringHashMap<FileStat*>::Type StatCache::Paths
Definition at line 34 of file stat_cache.h.
Member Function Documentation
void StatCache::Dump ()
Dump the mapping to stdout (useful for debugging).
Definition at line 30 of file stat_cache.cc.
References Node::dirty_, FileStat::node_, FileStat::path_, paths_, and FileStat::status_known().
FileStat * StatCache::GetFile (const std::string & path)
Definition at line 21 of file stat_cache.cc.
References paths_.
Referenced by State::GetNode(), and State::LookupNode().
void StatCache::Invalidate ()
Definition at line 40 of file stat_cache.cc.
References paths_.
Referenced by State::Reset().
Member Data Documentation
Paths StatCache::paths_
Definition at line 35 of file stat_cache.h.
Referenced by Dump(), GetFile(), and Invalidate().
The documentation for this struct was generated from the following files:
stat_cache.h
stat_cache.cc