Ninja: Tokenizer Struct Reference
Tokenizer Struct Reference
Processes an input stream into Tokens.
#include <parsers.h>
Public Member Functions
void ConsumeToken ()
bool Error (const string &message, string *err)
Report an error with a location pointing at the current token.
bool ErrorAt (const char *pos, const string &message, string *err)
Report an error at a particular location.
bool ErrorExpected (const string &expected, string *err)
Call Error() with "expected foo, got bar".
bool ExpectIdent (const char *expected, string *err)
bool ExpectToken (Token::Type expected, string *err)
bool Newline (string *err)
Token::Type PeekToken ()
bool ReadIdent (StringPiece *out)
bool ReadIdent (string *out)
bool ReadToNewline (string *text, string *err, size_t max_length=std::numeric_limits< size_t >::max())
void SetMakefileFlavor ()
Tokenization differs slightly between ninja files and Makefiles.
void SkipWhitespace (bool newline=false)
void Start (const char *start, const char *end)
const Token & token () const
Tokenizer ()
Public Attributes
const char * cur_
Start of the input.
int cur_indent_
const char * cur_line_
End of the input.
const char * end_
Current position within the input.
int last_indent_
bool makefile_flavor_
const char * start_
Token token_
Start of current line.
Detailed Description
Processes an input stream into Tokens.
Definition at line 54 of file parsers.h.
Constructor & Destructor Documentation
Tokenizer::Tokenizer () [inline]
Definition at line 55 of file parsers.h.
Member Function Documentation
void Tokenizer::ConsumeToken ()
Definition at line 270 of file parsers.cc.
References Token::Clear(), and token_.
Referenced by ExpectIdent(), ExpectToken(), ManifestParser::ParseEdge(), ManifestParser::ParseRule(), and ReadIdent().
bool Tokenizer::Error (const string & message, string * err) [inline]
Report an error with a location pointing at the current token.
Definition at line 71 of file parsers.h.
Referenced by ErrorExpected(), ManifestParser::Parse(), ManifestParser::ParseDefaults(), ManifestParser::ParseEdge(), ManifestParser::ParseFileInclude(), ManifestParser::ParseLetValue(), ManifestParser::ParseRule(), and ReadToNewline().
bool Tokenizer::ErrorAt (const char * pos, const string & message, string * err)
Report an error at a particular location.
Definition at line 44 of file parsers.cc.
References start_.
Referenced by ManifestParser::ParseRule().
bool Tokenizer::ErrorExpected (const string & expected, string * err)
Call Error() with "expected foo, got bar".
Definition at line 69 of file parsers.cc.
References Token::AsString(), Error(), and token_.
Referenced by ExpectIdent(), ExpectToken(), MakefileParser::Parse(), ManifestParser::ParseDefaults(), ManifestParser::ParseEdge(), ManifestParser::ParseFileInclude(), ManifestParser::ParseLetKey(), and ManifestParser::ParseRule().
bool Tokenizer::ExpectIdent (const char * expected, string * err)
Definition at line 141 of file parsers.cc.
References ConsumeToken(), Token::end_, ErrorExpected(), Token::IDENT, PeekToken(), Token::pos_, token_, and Token::type_.
Referenced by ManifestParser::ParseDefaults(), ManifestParser::ParseEdge(), and ManifestParser::ParseRule().
bool Tokenizer::ExpectToken (Token::Type expected, string * err)
Definition at line 133 of file parsers.cc.
References ConsumeToken(), ErrorExpected(), PeekToken(), token_, and Token::type_.
Referenced by Newline(), MakefileParser::Parse(), and ManifestParser::ParseLetKey().
bool Tokenizer::Newline (string * err)
Definition at line 98 of file parsers.cc.
References ExpectToken(), and Token::NEWLINE.
Referenced by ManifestParser::ParseDefaults(), ManifestParser::ParseEdge(), ManifestParser::ParseFileInclude(), ManifestParser::ParseRule(), ReadToNewline(), and SkipWhitespace().
Token::Type Tokenizer::PeekToken ()
Definition at line 210 of file parsers.cc.
References Token::COLON, cur_, cur_indent_, cur_line_, Token::end_, end_, Token::EQUALS, Token::IDENT, Token::INDENT, IsIdentChar(), last_indent_, makefile_flavor_, Token::NEWLINE, Token::NONE, Token::OUTDENT, Token::PIPE, Token::PIPE2, Token::pos_, SkipWhitespace(), Token::TEOF, token_, Token::type_, and Token::UNKNOWN.
Referenced by ExpectIdent(), ExpectToken(), MakefileParser::Parse(), ManifestParser::Parse(), ManifestParser::ParseEdge(), ManifestParser::ParseRule(), and ReadIdent().
bool Tokenizer::ReadIdent (StringPiece * out)
Definition at line 151 of file parsers.cc.
References ConsumeToken(), Token::end_, Token::IDENT, StringPiece::len_, PeekToken(), Token::pos_, StringPiece::str_, token_, and Token::type_.
Referenced by MakefileParser::Parse(), ManifestParser::ParseDefaults(), ManifestParser::ParseEdge(), ManifestParser::ParseFileInclude(), ManifestParser::ParseLetKey(), ManifestParser::ParseRule(), and ReadIdent().
bool Tokenizer::ReadIdent (string * out)
Definition at line 161 of file parsers.cc.
References StringPiece::len_, ReadIdent(), StringPiece::str_, and token().
bool Tokenizer::ReadToNewline (string * text, string * err, size_t max_length = std::numeric_limits<size_t>::max())
Definition at line 181 of file parsers.cc.
References cur_, end_, Error(), makefile_flavor_, Newline(), Token::pos_, SkipWhitespace(), and token_.
Referenced by ManifestParser::ParseLetValue(), and ManifestParser::ParseRule().
void Tokenizer::SetMakefileFlavor () [inline]
Tokenization differs slightly between ninja files and Makefiles.
By default we tokenize as ninja files; calling this changes to Makefile-style tokenization.
Definition at line 63 of file parsers.h.
Referenced by MakefileParser::MakefileParser().
void Tokenizer::SkipWhitespace (bool newline = false)
Definition at line 73 of file parsers.cc.
References cur_, cur_line_, end_, makefile_flavor_, Token::NEWLINE, Newline(), token_, and Token::type_.
Referenced by MakefileParser::Parse(), ManifestParser::Parse(), PeekToken(), and ReadToNewline().
void Tokenizer::Start (const char * start, const char * end)
Definition at line 64 of file parsers.cc.
References cur_, cur_line_, end_, and start_.
Referenced by MakefileParser::Parse(), and ManifestParser::Parse().
const Token& Tokenizer::token () const [inline]
Definition at line 77 of file parsers.h.
Referenced by ManifestParser::Parse(), and ReadIdent().
Member Data Documentation
const char* Tokenizer::cur_
Start of the input.
Definition at line 94 of file parsers.h.
Referenced by PeekToken(), ReadToNewline(), SkipWhitespace(), and Start().
int Tokenizer::cur_indent_
Definition at line 99 of file parsers.h.
Referenced by PeekToken().
const char* Tokenizer::cur_line_
End of the input.
Definition at line 97 of file parsers.h.
Referenced by PeekToken(), SkipWhitespace(), and Start().
const char* Tokenizer::end_
Current position within the input.
Definition at line 95 of file parsers.h.
Referenced by PeekToken(), ReadToNewline(), SkipWhitespace(), and Start().
int Tokenizer::last_indent_
Definition at line 99 of file parsers.h.
Referenced by PeekToken().
bool Tokenizer::makefile_flavor_
Definition at line 91 of file parsers.h.
Referenced by PeekToken(), ReadToNewline(), and SkipWhitespace().
const char* Tokenizer::start_
Definition at line 93 of file parsers.h.
Referenced by ErrorAt(), and Start().
Token Tokenizer::token_
Start of current line.
Definition at line 98 of file parsers.h.
Referenced by ConsumeToken(), ErrorExpected(), ExpectIdent(), ExpectToken(), ManifestParser::ParseRule(), PeekToken(), ReadIdent(), ReadToNewline(), and SkipWhitespace().
The documentation for this struct was generated from the following files:
parsers.h
parsers.cc