Ninja: ManifestParser Struct Reference
ManifestParser Struct Reference
Parses .ninja files.
#include <parsers.h>
Classes
struct FileReader
Public Member Functions
bool Load (const string &filename, string *err)
ManifestParser (State *state, FileReader *file_reader)
bool Parse (const string &input, string *err)
bool ParseDefaults (string *err)
bool ParseEdge (string *err)
bool ParseFileInclude (string *err)
Parse either a 'subninja' or 'include' line.
bool ParseLet (string *key, string *val, string *err)
Parse a key=val statement, expanding $vars in the value with the current env.
bool ParseLetKey (string *key, string *err)
Parse the "key=" half of a key=val statement.
bool ParseLetValue (EvalString *eval, string *err)
Parse the val half of a key=val statement, writing and parsing output into an EvalString (ready for expansion).
bool ParseRule (string *err)
Public Attributes
BindingEnv * env_
FileReader * file_reader_
State * state_
Tokenizer tokenizer_
Detailed Description
Parses .ninja files.
Definition at line 116 of file parsers.h.
Constructor & Destructor Documentation
ManifestParser::ManifestParser (State * state, FileReader * file_reader)
Definition at line 300 of file parsers.cc.
References State::bindings_, and env_.
Member Function Documentation
bool ManifestParser::Load (const string & filename, string * err)
Definition at line 304 of file parsers.cc.
References file_reader_, Parse(), and ManifestParser::FileReader::ReadFile().
Referenced by main().
bool ManifestParser::Parse (const string & input, string * err)
Definition at line 311 of file parsers.cc.
References BindingEnv::AddBinding(), Token::AsString(), Token::end_, env_, Tokenizer::Error(), Token::IDENT, ParseDefaults(), ParseEdge(), ParseFileInclude(), ParseLet(), ParseRule(), Tokenizer::PeekToken(), Token::pos_, Tokenizer::SkipWhitespace(), Tokenizer::Start(), Token::TEOF, Tokenizer::token(), tokenizer_, and Token::type_.
Referenced by ParserTest::AssertParse(), AssertParse(), Load(), ParseFileInclude(), and TEST_F().
bool ManifestParser::ParseDefaults (string * err)
Definition at line 463 of file parsers.cc.
References State::AddDefault(), CanonicalizePath(), env_, Tokenizer::Error(), Tokenizer::ErrorExpected(), EvalString::Evaluate(), Tokenizer::ExpectIdent(), Tokenizer::Newline(), EvalString::Parse(), Tokenizer::ReadIdent(), state_, and tokenizer_.
Referenced by Parse().
bool ManifestParser::ParseEdge (string * err)
Definition at line 489 of file parsers.cc.
References BindingEnv::AddBinding(), State::AddEdge(), State::AddIn(), State::AddOut(), CanonicalizePath(), Token::COLON, Tokenizer::ConsumeToken(), Edge::env_, env_, Tokenizer::Error(), Tokenizer::ErrorExpected(), EvalString::Evaluate(), Tokenizer::ExpectIdent(), Edge::implicit_deps_, Token::INDENT, State::LookupRule(), Tokenizer::Newline(), Edge::order_only_deps_, Token::OUTDENT, BindingEnv::parent_, EvalString::Parse(), ParseLet(), Tokenizer::PeekToken(), Token::PIPE, Token::PIPE2, Tokenizer::ReadIdent(), state_, and tokenizer_.
Referenced by Parse().
bool ManifestParser::ParseFileInclude (string * err)
Parse either a 'subninja' or 'include' line.
Definition at line 600 of file parsers.cc.
References env_, Tokenizer::Error(), Tokenizer::ErrorExpected(), file_reader_, Tokenizer::Newline(), BindingEnv::parent_, Parse(), ManifestParser::FileReader::ReadFile(), Tokenizer::ReadIdent(), state_, and tokenizer_.
Referenced by Parse().
bool ManifestParser::ParseLet (string * key, string * val, string * err)
Parse a key=val statement, expanding $vars in the value with the current env.
Definition at line 418 of file parsers.cc.
References env_, EvalString::Evaluate(), ParseLetKey(), and ParseLetValue().
Referenced by Parse(), and ParseEdge().
bool ManifestParser::ParseLetKey (string * key, string * err)
Parse the "key=" half of a key=val statement.
Definition at line 431 of file parsers.cc.
References Token::EQUALS, Tokenizer::ErrorExpected(), Tokenizer::ExpectToken(), Tokenizer::ReadIdent(), and tokenizer_.
Referenced by ParseLet(), and ParseRule().
bool ManifestParser::ParseLetValue (EvalString * eval, string * err)
Parse the val half of a key=val statement, writing and parsing output into an EvalString (ready for expansion).
Definition at line 439 of file parsers.cc.
References Tokenizer::Error(), EvalString::Parse(), Tokenizer::ReadToNewline(), and tokenizer_.
Referenced by ParseLet(), and ParseRule().
bool ManifestParser::ParseRule (string * err)
Definition at line 353 of file parsers.cc.
References State::AddRule(), Rule::command_, Tokenizer::ConsumeToken(), Rule::depfile_, Rule::description_, Tokenizer::Error(), Tokenizer::ErrorAt(), Tokenizer::ErrorExpected(), Tokenizer::ExpectIdent(), Rule::generator_, Token::INDENT, State::LookupRule(), Tokenizer::Newline(), Token::OUTDENT, ParseLetKey(), ParseLetValue(), Tokenizer::PeekToken(), Token::pos_, Tokenizer::ReadIdent(), Tokenizer::ReadToNewline(), Rule::restat_, state_, Tokenizer::token_, tokenizer_, and EvalString::unparsed().
Referenced by Parse().
Member Data Documentation
BindingEnv* ManifestParser::env_
Definition at line 145 of file parsers.h.
Referenced by ManifestParser(), Parse(), ParseDefaults(), ParseEdge(), ParseFileInclude(), and ParseLet().
FileReader* ManifestParser::file_reader_
Definition at line 146 of file parsers.h.
Referenced by Load(), and ParseFileInclude().
State* ManifestParser::state_
Definition at line 144 of file parsers.h.
Referenced by ParseDefaults(), ParseEdge(), ParseFileInclude(), and ParseRule().
Tokenizer ManifestParser::tokenizer_
Definition at line 147 of file parsers.h.
Referenced by Parse(), ParseDefaults(), ParseEdge(), ParseFileInclude(), ParseLetKey(), ParseLetValue(), and ParseRule().
The documentation for this struct was generated from the following files:
parsers.h
parsers.cc