Ninja: MakefileParser Struct Reference
MakefileParser Struct Reference
Parses simple Makefiles as generated by gcc.
#include <parsers.h>
Public Member Functions
MakefileParser ()
bool Parse (const string &input, string *err)
Public Attributes
vector< StringPiece > ins_
StringPiece out_
Tokenizer tokenizer_
Detailed Description
Parses simple Makefiles as generated by gcc.
Definition at line 103 of file parsers.h.
Constructor & Destructor Documentation
MakefileParser::MakefileParser ()
Definition at line 274 of file parsers.cc.
References Tokenizer::SetMakefileFlavor(), and tokenizer_.
Member Function Documentation
bool MakefileParser::Parse (const string & input, string * err)
Definition at line 278 of file parsers.cc.
References Token::COLON, Tokenizer::ErrorExpected(), Tokenizer::ExpectToken(), Token::IDENT, ins_, Token::NEWLINE, out_, Tokenizer::PeekToken(), Tokenizer::ReadIdent(), Tokenizer::SkipWhitespace(), Tokenizer::Start(), Token::TEOF, and tokenizer_.
Referenced by Edge::LoadDepFile(), main(), and TEST().
Member Data Documentation
vector<StringPiece> MakefileParser::ins_
Definition at line 109 of file parsers.h.
Referenced by Edge::LoadDepFile(), Parse(), and TEST().
StringPiece MakefileParser::out_
Definition at line 108 of file parsers.h.
Referenced by Edge::LoadDepFile(), Parse(), and TEST().
Tokenizer MakefileParser::tokenizer_
Definition at line 107 of file parsers.h.
Referenced by MakefileParser(), and Parse().
The documentation for this struct was generated from the following files:
parsers.h
parsers.cc