Ninja: BuildTest Struct Reference
BuildTest Struct Reference
Public Member Functions
BuildTest ()
virtual bool CanRunMore ()
void Dirty (const string &path)
Node * GetNode (const string &path)
BuildConfig MakeConfig ()
virtual bool StartCommand (Edge *edge)
virtual Edge * WaitForCommand (bool *success, string *output)
Wait for a command to complete.
Public Attributes
Builder builder_
vector< string > commands_ran_
BuildConfig config_
VirtualFileSystem fs_
Edge * last_command_
int now_
State state_
Detailed Description
Definition at line 179 of file build_test.cc.
Constructor & Destructor Documentation
BuildTest::BuildTest () [inline]
Definition at line 181 of file build_test.cc.
References AssertParse(), builder_, Builder::command_runner_, VirtualFileSystem::Create(), Builder::disk_interface_, fs_, now_, and StateTestWithBuiltinRules::state_.
Member Function Documentation
bool BuildTest::CanRunMore () [virtual]
Implements CommandRunner.
Definition at line 228 of file build_test.cc.
References last_command_.
void BuildTest::Dirty (const string & path)
Definition at line 218 of file build_test.cc.
References Node::dirty_, Node::file_, StateTestWithBuiltinRules::GetNode(), Node::in_edge_, and FileStat::mtime_.
Node * StateTestWithBuiltinRules::GetNode (const string & path) [inherited]
Definition at line 25 of file test.cc.
References State::GetNode(), and StateTestWithBuiltinRules::state_.
Referenced by Dirty().
BuildConfig BuildTest::MakeConfig () [inline]
Definition at line 202 of file build_test.cc.
References BuildConfig::QUIET, and BuildConfig::verbosity.
bool BuildTest::StartCommand (Edge * edge) [virtual]
Implements CommandRunner.
Definition at line 233 of file build_test.cc.
References commands_ran_, VirtualFileSystem::Create(), Edge::EvaluateCommand(), fs_, last_command_, Rule::name_, now_, Edge::outputs_, and Edge::rule_.
Edge * BuildTest::WaitForCommand (bool * success, string * output) [virtual]
Wait for a command to complete.
Implements CommandRunner.
Definition at line 254 of file build_test.cc.
References last_command_.
Member Data Documentation
Builder BuildTest::builder_
Definition at line 209 of file build_test.cc.
Referenced by BuildTest(), and BuildWithLogTest::BuildWithLogTest().
vector<string> BuildTest::commands_ran_
Definition at line 214 of file build_test.cc.
Referenced by StartCommand().
BuildConfig BuildTest::config_
Definition at line 208 of file build_test.cc.
VirtualFileSystem BuildTest::fs_
Definition at line 212 of file build_test.cc.
Referenced by BuildTest(), and StartCommand().
Edge* BuildTest::last_command_
Definition at line 215 of file build_test.cc.
Referenced by CanRunMore(), StartCommand(), and WaitForCommand().
int BuildTest::now_
Definition at line 210 of file build_test.cc.
Referenced by BuildTest(), and StartCommand().
State StateTestWithBuiltinRules::state_ [inherited]
Definition at line 33 of file test.h.
Referenced by BuildTest(), BuildWithLogTest::BuildWithLogTest(), StateTestWithBuiltinRules::GetNode(), and StateTestWithBuiltinRules::StateTestWithBuiltinRules().
The documentation for this struct was generated from the following file:
build_test.cc