Ninja: test.h File Reference
test.h File Reference
#include <gtest/gtest.h>
#include "disk_interface.h"
#include "state.h"
Classes
struct VirtualFileSystem::Entry
An entry for a single in-memory file.
struct StateTestWithBuiltinRules
A base test fixture that includes a State object with a builtin "cat" rule.
struct VirtualFileSystem
An implementation of DiskInterface that uses an in-memory representation of disk state.
Functions
void AssertParse (State *state, const char *input)
Function Documentation
void AssertParse (State * state, const char * input)
Definition at line 29 of file test.cc.
References ManifestParser::Parse().
Referenced by BuildTest::BuildTest(), StateTestWithBuiltinRules::StateTestWithBuiltinRules(), and TEST_F().