Ninja: test.cc File Reference
test.cc File Reference
#include "test.h"
#include "parsers.h"
Functions
void AssertParse (State *state, const char *input)
Function Documentation
void AssertParse (State * state, const char * input)
Definition at line 29 of file test.cc.
References ManifestParser::Parse().
Referenced by BuildTest::BuildTest(), StateTestWithBuiltinRules::StateTestWithBuiltinRules(), and TEST_F().