Ninja: util_test.cc File Reference
util_test.cc File Reference
#include "util.h"
#include "test.h"
Functions
TEST (CanonicalizePath, PathSamples)
TEST (CanonicalizePath, UpDir)
TEST (CanonicalizePath, AbsolutePath)
Function Documentation
TEST (CanonicalizePath , PathSamples)
Definition at line 19 of file util_test.cc.
References CanonicalizePath().
TEST (CanonicalizePath , UpDir)
Definition at line 59 of file util_test.cc.
References CanonicalizePath().
TEST (CanonicalizePath , AbsolutePath)
Definition at line 70 of file util_test.cc.
References CanonicalizePath().